### ISSUE TITLE
Font Rendering in OpenGL

### ISSUE THREAD

**Issue by pathway27** [pathway27/bookr-mod-vita#1]
https://wildfiregames.com/forum/index.php?/topic/17365-freetype-ttf-fonts-in-opengl/

**Comment by ebraminio** [comment]
If we could bring something like http://www.pango.org that would be best as it supports lots of things out of the box like complex scripts rendering and such however that would be a hard task, for starters, it needs harfbuzz and cairo itself which itself would be hard task I guess. Also pango doesn't provide a cmake file but https://github.com/Microsoft/vcpkg/blob/master/ports/pango/CMakeLists.txt can be used I guess.

**Comment by ebraminio** [comment]
Simpler solutions are also possible like this https://github.com/ebraminio/glcourse/blob/master/hello-harfbuzz-gl.cc

**Comment by Invictaz** [comment]
Maybe use VitaGL? It's recently been added to VitaSDK

**Comment by pathway27** [comment]
Oh really, I'll check it out. Thanks!

**Comment by Invictaz** [comment]
@pathway27 https://twitter.com/Rinnegatamante/status/1274297243315703808?s=19

**Comment by ebraminio** [comment]
Does it do font rendering? Wished could suggest libraqm https://github.com/HOST-Oman/libraqm#projects-using-raqm but first I have to put fribidi and raqm to packages https://github.com/vitasdk/packages

**Comment by Invictaz** [comment]
@ebraminio not sure. However intra font like on the psp should be avoided on Vita.

**Comment by pathway27** [comment]
Freetype is fine.
