### ISSUE TITLE
Putting system to sleep causes pages to turn blank.

### ISSUE THREAD

**Issue by Missingmew** [pathway27/bookr-mod-vita#13]
When reading a PDF document, putting the system to sleep and waking it back up causes all pages loaded afterwards to turn into blank ones (even if you do a next+prev combo, the page that was loaded when going to sleep will turn blank).
Steps:
1. Load a document
2. Put system to sleep (no difference between just turning the screen off and "deep sleep" where the power LED goes off)
3. wake system back up
4. load a new page, page will be blank

A reload of the document will return everything to normal (and since the last viewed page is saved on opening a new document, reading where you left off is almost seamless).

**Comment by pathway27** [comment]
Thanks for the report, will be fixed in the next release. :)

**Comment by bopz44** [comment]
Missingmew, if you cant wait for next release you can still install repatch plugin https://github.com/dots-tb/rePatch-reDux0/releases/tag/2.69 that solves suspended issues with bookr or even retroarch.
