### ISSUE TITLE
Fit to Width/Height aren't working properly in portrait mode.

### ISSUE THREAD

**Issue by KawaiiAurora** [pathway27/bookr-mod-vita#15]
Hey,
I just updated to Bookr Mod 0.3 and was quite excited with the ability to rotate the Vita's screen to portrait mode. Unfortunately, fit to width/height aren't working properly and content looks quite odd. The attached screenshots demonstrate the issues I'm encountering.

Thanks,
Aurora

![2018-09-16-214417](https://user-images.githubusercontent.com/24445020/45600532-6610aa00-b9fe-11e8-9e25-f7da7d2b98af.jpg)
![2018-09-16-214300](https://user-images.githubusercontent.com/24445020/45600534-6c068b00-b9fe-11e8-8063-b8a70ed84038.jpg)

**Comment by pathway27** [comment]
Thanks for catching this! I think I've figured out why this is happening.

**Comment by pathway27** [comment]
Should be fixed now in v0.3.1.
