### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by rika09** [pathway27/bookr-mod-vita#16]
Can you make it bigger than 20? (or is this even working i cant realy see diffrence) Its to small to read.

**Comment by pathway27** [comment]
Yeah the font size doesn't work on PDFs and such. Try zooming by pressing the R trigger.

**Comment by pathway27** [comment]
See the [latest release](https://github.com/pathway27/bookr-mod-vita/releases/tag/v0.4.0a). Feel free to re-open this with any issues.
