### ISSUE TITLE
Fit to Width/Height aren't working properly in portrait mode

### ISSUE THREAD

**Issue by snip71** [pathway27/bookr-mod-vita#17]
it still has this bug in latest version :( i love this app. ps vita deserve a decent ebook reader
tanx for your effort

**Comment by snip71** [comment]
plz fix this

**Comment by pathway27** [comment]
Looking into this.
Could you tell me what kind of e-book you're reading?

**Comment by snip71** [comment]
Im reading epub files. I tried different files and every one of them had this problem.

**Comment by pathway27** [comment]
Could you send me a screenshot of this as well as the about page?

**Comment by snip71** [comment]
![2018-12-13-165616](https://user-images.githubusercontent.com/44939541/49941677-6d116080-fef8-11e8-895d-14482eac0719.jpg)
![2018-12-13-165607](https://user-images.githubusercontent.com/44939541/49941682-726eab00-fef8-11e8-81db-c7ace6ae22dc.jpg)
its a sample
all my epubs in portrait mode display like this.
they have issue with height and width fitting.

**Comment by snip71** [comment]
plz fix this.
if it has a look like ibooks on ios devices, it will be amazing.
thank u

**Comment by pathway27** [comment]
Can you also give me a screenshot of the "About" page? You can find it on the Main Menu.

I will try to do that, yes.

**Comment by snip71** [comment]
![2018-12-17-180537](https://user-images.githubusercontent.com/44939541/50093953-42d8df00-0227-11e9-83bb-f2c117533f1f.jpg)
here, this is About page.
tnx

**Comment by ebraminio** [comment]
Hey @pathway27 thanks a lot for mentioning me, glad that I've helped :P

**Comment by snip71** [comment]
@pathway27 i hope u didn't forgot about this project :(

**Comment by pathway27** [comment]
Sorry had to move countries for work. I'll get to this soon.

**Comment by ebraminio** [comment]
@pathway27 Oh thanks for all the works.

**Comment by pathway27** [comment]
So @snip71 , I've looked into this and what you're see is the correct result when you fit to height after rotating.

I think I know what you need but It will a big re-write. Until then, I'm closing this issue.
Hopefully It will be more like iBooks after.
