### ISSUE TITLE
White images/crashes due to zoom

### ISSUE THREAD

**Issue by donutholer** [pathway27/bookr-mod-vita#18]
Pages in the current release of bookr are often blank. 
File type: PDF (20-100mbs)
Zooming (with shoulder buttons) too far in or too far out cause the app to crash

**Comment by pathway27** [comment]
Yeah, looking into this.

**Comment by donutholer** [comment]
I've noticed a weird inconsistency with the white pages as well. It occurs randomly and can vary from 1-10 ish blank pages.  Sometimes it loads sometimes it doesn't

**Comment by pathway27** [comment]
Yes, I'm seeing this now too.
Let me compile with newer `mupdf` and see if that helps.

**Comment by donutholer** [comment]
Great. Other than that, all the functions are working flawlessly, keep it
up :)

**Comment by OM532** [comment]
What about new release? Compiled it myself, but it crashes on launch.

**Comment by donutholer** [comment]
I'll give it a try tonight. Thanks!

**Comment by donutholer** [comment]
> Yes, I'm seeing this now too.
> Let me compile with newer `mupdf` and see if that helps.

How did this go? Is it worth trying this myself as well?

**Comment by pathway27** [comment]
Slow but I'm close, tying this up with a potential switch release.

**Comment by OM532** [comment]
Any progress?

**Comment by pathway27** [comment]
See above.

**Comment by OM532** [comment]
bump

**Comment by pathway27** [comment]
Sorry for the delays, just hold on a bit longer.

**Comment by Invictaz** [comment]
@pathway27 Any news on this?

**Comment by pathway27** [comment]
Back on it!

**Comment by benpage11** [comment]
Having the same problem as well with large CBZ pages. Any luck fixing it?

**Comment by pathway27** [comment]
I think I have a solution, hang tight

**Comment by pathway27** [comment]
See the [latest release](https://github.com/pathway27/bookr-mod-vita/releases/tag/v0.4.0a). Feel free to re-open this with any issues.
