### ISSUE TITLE
Support for other storage partitions?

### ISSUE THREAD

**Issue by zemmyang** [pathway27/bookr-mod-vita#25]
Seems like I can only see files in ux0, which is generally not a problem, but I want to use the official vita memory card (mounted in ux0) as well as other storage locations (like, say, a sd2vita in uma0).

Is there a way to view files in other partitions?

**Comment by pathway27** [comment]
See the [latest release](https://github.com/pathway27/bookr-mod-vita/releases/tag/v0.4.0a). Feel free to re-open this with any issues.
