### ISSUE TITLE
Crashes when zoom past 1.7x

### ISSUE THREAD

**Issue by ralphieb2t** [pathway27/bookr-mod-vita#26]
Not sure if this is still being worked on, nor am I sure if I have the most recent version. But I use Bookr very often and it displays most pdf & epub just fine. However, the text is just far too small! You cannot make it much bigger and whenever I attempt to zoom past 1.7x it crashes while “zooming to 1.8x” everytime. I use this very often, as it is one of few decent pdf viewers for the Vita however the font just comes up much too small. Without at least a rudimentary way to adjust, it is not functional.

**Comment by pathway27** [comment]
Still working on it, albiet a bit slower. Covid really messed my year of progress. I'm closer to releasing a new version.

Stay safe,

**Comment by pathway27** [comment]
See the [latest release](https://github.com/pathway27/bookr-mod-vita/releases/tag/v0.4.0a). Feel free to re-open this with any issues.
