### ISSUE TITLE
Can't open plain text epub

### ISSUE THREAD

**Issue by joelmzj** [pathway27/bookr-mod-vita#27]
I've tried many times to open a epub, but app closes immediately.

Also, could youl compile the source with the latest commits? It could be a testing package. I love your app, I use it every day and I'd be very glad to be a tester.

Thanks in advance.

**Comment by pathway27** [comment]
Sure, expect something on this coming Sunday.

**Comment by pathway27** [comment]
Also, could you leave link problematic `epub`  by chance?

**Comment by pathway27** [comment]
See the [latest release](https://github.com/pathway27/bookr-mod-vita/releases/tag/v0.4.0a). Feel free to re open this with any issues.
