### ISSUE TITLE
Cannot open large files

### ISSUE THREAD

**Issue by azumukupoe** [pathway27/bookr-mod-vita#5]
I know it is a problem existing from PSP version, but isn't there a way to display larger files on Vita?

**Comment by pathway27** [comment]
Yeah I too have faced this on the PSP, thanks for reminding me.
I feel like the Vita can do it.

How big were your files and what format were they?

**Comment by pathway27** [comment]
I've doubled the heap memory in the latest version, it's handling my 1GB CBZ fine.

Re-open this issue if your file isn't displaying.
