### ISSUE TITLE
No file display

### ISSUE THREAD

**Issue by duongquang1701** [pathway27/bookr-mod-vita#8]
i installed bookr 0.21 on my vita and download some ePub files. But when I opened my ebooks folder there was nothing except txt file! It is a great Hb app and I really want to read books. Pls help. Sorry for bad engrisk :)

**Comment by duongquang1701** [comment]
pdf 2.8mb epub 0.2mb

**Comment by pathway27** [comment]
Could you screenshot the folder in bookr and VitaShell?

**Comment by duongquang1701** [comment]
OK im going to do it right now

**Comment by duongquang1701** [comment]
https://ibb.co/ncGyFx
https://ibb.co/gkUUNc

**Comment by pathway27** [comment]
Hmm, that's very weird. Are you using SD2Vita?
 
What do you see at ux0: (one level up) in Bookr?

**Comment by duongquang1701** [comment]
Yeah im using sd2 vita

**Comment by duongquang1701** [comment]
And bookr only display ux0 folder

**Comment by duongquang1701** [comment]
https://ibb.co/nqQ3yH

**Comment by pathway27** [comment]
Can you press up and see any files from there? At the bottom.

**Comment by duongquang1701** [comment]
https://ibb.co/fZgPoH 
Here they are! :D

**Comment by pathway27** [comment]
Try put your books there.

**Comment by duongquang1701** [comment]
I did . But as u see. No books are display except txt :(

**Comment by pathway27** [comment]
Feels like a permission issue.

Can you try FTP the books again directly to ux0:data/Bookr and see if you can find them.

Also, what program are you using to FTP? FileZilla?

**Comment by duongquang1701** [comment]
:) i downloaded through browser. You are right about permission issue,I think

**Comment by duongquang1701** [comment]
I don't have pc. It will be a big problem

**Comment by pathway27** [comment]
That's ok then.

Can you try use VitaShell to move the files to ux0:data/Bookr then see if they're visible?

**Comment by duongquang1701** [comment]
Let me try

**Comment by duongquang1701** [comment]
I have moved ebooks to ux0:data/bookr. When I open bookr . The folder ux0:data  is not displayed

**Comment by duongquang1701** [comment]
Ah yes it was there. But there is no books :D then

**Comment by duongquang1701** [comment]
Do u think download enabler plugin  did something to my ebooks?

**Comment by pathway27** [comment]
Ok, I can replicate your issue.

Yes the Download Enabler plugin makes the files hidden to safe homebrew like mine.
The easiest fix is to use FTP to transfer to computer then back via VitaShell.

If you cannot do that i've made a special unsafe vpk: https://github.com/pathway27/bookr-mod-vita/releases/download/v0.2.1/bookr-mod-vita-unsafe.vpk.

Note: I really don't want to make future releases unsafe, so best bet I'll either raise an issue with that plugin or make VitaShell able to unhide these files/folders.

**Comment by duongquang1701** [comment]
Thank ya so much :)

**Comment by duongquang1701** [comment]
How about switching to safe homebrew when using this app? Guess u will have many thing to do
