### ISSUE TITLE
Bookr crashing

### ISSUE THREAD

**Issue by BriskIcedTea** [pathway27/bookr-mod-vita#9]
When reading a manga in cbz format(only one I have used so far) then putting the vita to sleep then waking the vita and turning a page the app will close out to the LiveArea

**Comment by pathway27** [comment]
Good catch, I think i've figured out why.

**Comment by bopz44** [comment]
Hi pathway, don't know if you already fixed the issue but wanna let you know since 1.0 release of rePatch plugin (https://github.com/dots-tb/rePatch-reDux0) the suspended issue is now gone !

**Comment by pathway27** [comment]
Oh really? I did fix it, but haven't released it yet. Thanks for the info! 😄 

Weird that a plugin fixes this issue though. I'll give it a test soon.
